version: "3.8"

services:
  api:
    build:
    container_name: fastapi_backend
    ports:
     -"8000:8000"
    depends_on:
      -redis
      -db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5431/mydatabase 
      - CELERY_BROKEN_URL=redis://localhost:6380/0
      - CELERY_RESULT_BACKEND=redis://localhost:6380/0

redis:
  image: redis:7.0
  container_name: redis_cache
  ports:
    - "6379:6380"

db:
  image: postgres:15
  container_name: postgres_db
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: password
   POSTGRES_DB: mydatabase
  ports:
   - "5432:5432"

celery:
  build:
  conatiner_name: celery_worker
  command: celery -A src.celery_app worker --loglevel=info
  depends_on:
   -redis
   -api

flower:
  image: mher/flower
  container_name: flower_dashboard
  ports:
   - "5555:5555"
  environment:
   -  CELERY_BROKEN_URL=redis://localhost:6380/0
  depends_on:
   - celery 